### ISSUE TITLE
Ubuntu 16.04.6 LTS & daemonize package issue

### ISSUE THREAD

**Issue by MedAnd** [shayne/wsl2-hacks#2]
Trying to follow the guide by running:

> sudo apt install dbus policykit-1 daemonize

**Output:** 

E: Unable to locate package daemonize

**Comment by shayne** [comment]
You can build from source.

```
$ sudo apt-get install build-essential
```

Source is https://github.com/bmc/daemonize

```
daemonize/ $ ./configure
daemonize/ $ make
daemonize/ $ sudo make install
```
