### ISSUE TITLE
Update instructions for Ubuntu 20.04

### ISSUE THREAD

**Issue by rubys** [shayne/wsl2-hacks#9]
Three changes are required:
  
  - The first, and most minor, is to change where it says `ubuntu1804.exe`,  and replace that with `ubuntu2004.exe`.
  - Next, I found that ubuntu already had a `/usr/bin/bash`, so go with something like `/usr/bin/bash-bootstrap-services` instead.
  - Finally, and most troublesome, `daemonize` is now in `/usr/bin` instead of `/usr/sbin`.  The script, as written, will hang indefinitely.

Given the third problem, I would recommend that the steps in the instructions be run in a different order.  After step 1, jump to step 4. Then do step 3 (`sudo` will no longer be required at this point) and then **test the script** by running it.  If it logs you in as your user ID and the test in step 5 works, **then and only then** do step 3.

**Comment by Victor333Huesca** [comment]
Instructions may vary depending and the distro and the version. An alternative would be a have either one file per distro or to simply specify to patch to apply depending on the target in the comment section.
I will eventually do this this this week-end and publish a fork.

**Comment by rubys** [comment]
Addressed by other pull requests.
